config/routes.rb
Testsite2::Application.routes.draw do
  match 'user/edit' => 'users#edit', :as => :edit_current_user

  match 'signup' => 'users#new', :as => :signup

  match 'logout' => 'sessions#destroy', :as => :logout

  match 'login' => 'sessions#new', :as => :login

  root :to => 'accounts#new'

  resources :sessions

  match '/mobile/', :controller => 'mobile', :action => 'index'
  match '/mobile/:id', :controller => 'mobile', :action => 'show'
  match '/mobile/:id/observe', :controller => 'mobile', :action => 'observe'
  match '/mobile/:id/create_observation', :controller => 'mobile', :action => 'create_observation'

  get "sessions/new"
  
  resources :users

  resources :convention_delegates

  resources :observations

end

app/models/observation.rb
class Observation < ActiveRecord::Base
  belongs_to :convention_delegate
  belongs_to :user
end

app/controllers/observations_controller.rb
class ObservationsController < ApplicationController
  # GET /observations
  # GET /observations.json
  def index
    @observations = Observation.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @observations }
    end
  end

  # GET /observations/1
  # GET /observations/1.json
  def show
    @observation = Observation.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @observation }
    end
  end

  # GET /observations/new
  # GET /observations/new.json
  def new
    @observation = Observation.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @observation }
    end
  end

  # GET /observations/1/edit
  def edit
    @observation = Observation.find(params[:id])
  end

  # POST /observations
  # POST /observations.json
  def create
    @observation = Observation.new(params[:observation])

    respond_to do |format|
      if @observation.save
        format.html { redirect_to @observation, notice: 'Observation was successfully created.' }
        format.json { render json: @observation, status: :created, location: @observation }
      else
        format.html { render action: "new" }
        format.json { render json: @observation.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /observations/1
  # PUT /observations/1.json
  def update
    @observation = Observation.find(params[:id])

    respond_to do |format|
      if @observation.update_attributes(params[:observation])
        format.html { redirect_to @observation, notice: 'Observation was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @observation.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /observations/1
  # DELETE /observations/1.json
  def destroy
    @observation = Observation.find(params[:id])
    @observation.destroy

    respond_to do |format|
      format.html { redirect_to observations_url }
      format.json { head :ok }
    end
  end
end

app/helpers/observations_helper.rb
module ObservationsHelper
end

app/views/observations/_form.html.erb
<%= form_for(@observation) do |f| %>
  <% if @observation.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@observation.errors.count, "error") %> prohibited this observation from being saved:</h2>

      <ul>
      <% @observation.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :convention_delegate %><br />
    <%= f.text_field :convention_delegate %>
  </div>
  <div class="field">
    <%= f.label :user %><br />
    <%= f.text_field :user %>
  </div>
  <div class="field">
    <%= f.label :ip_address %><br />
    <%= f.text_field :ip_address %>
  </div>
  <div class="field">
    <%= f.label :user_agent %><br />
    <%= f.text_field :user_agent %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/observations/edit.html.erb
<h1>Editing observation</h1>

<%= render 'form' %>

<%= link_to 'Show', @observation %> |
<%= link_to 'Back', observations_path %>

app/views/observations/index.html.erb
<h1>Listing observations</h1>

<table>
  <tr>
    <th>Convention delegate</th>
    <th>User</th>
    <th>Ip address</th>
    <th>User agent</th>
    <th>Value</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @observations.each do |observation| %>
  <tr>
    <td><%= observation.convention_delegate %></td>
    <td><%= observation.user %></td>
    <td><%= observation.ip_address %></td>
    <td><%= observation.user_agent %></td>
    <td><%= observation.value %></td>
    <td><%= link_to 'Show', observation %></td>
    <td><%= link_to 'Edit', edit_observation_path(observation) %></td>
    <td><%= link_to 'Destroy', observation, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Observation', new_observation_path %>

app/views/observations/new.html.erb
<h1>New observation</h1>

<%= render 'form' %>

<%= link_to 'Back', observations_path %>

app/views/observations/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Convention delegate:</b>
  <%= @observation.convention_delegate %>
</p>

<p>
  <b>User:</b>
  <%= @observation.user %>
</p>

<p>
  <b>Ip address:</b>
  <%= @observation.ip_address %>
</p>

<p>
  <b>User agent:</b>
  <%= @observation.user_agent %>
</p>

<p>
  <b>Created:</b>
  <%= @observation.created %>
</p>


<%= link_to 'Edit', edit_observation_path(@observation) %> |
<%= link_to 'Back', observations_path %>