config/routes.rb
Testsite2::Application.routes.draw do
  match 'user/edit' => 'users#edit', :as => :edit_current_user

  match 'signup' => 'users#new', :as => :signup

  match 'logout' => 'sessions#destroy', :as => :logout

  match 'login' => 'sessions#new', :as => :login

  root :to => 'accounts#new'

  resources :sessions

  match '/mobile/', :controller => 'mobile', :action => 'index'
  match '/mobile/:id', :controller => 'mobile', :action => 'show'
  match '/mobile/:id/observe', :controller => 'mobile', :action => 'observe'
  match '/mobile/:id/create_observation', :controller => 'mobile', :action => 'create_observation'

  get "sessions/new"
  
  resources :users

  resources :convention_delegates

  resources :observations

end

app/models/convention_delegate.rb
class ConventionDelegate < ActiveRecord::Base
  has_many :obervation
end

app/controllers/convention_delegates_controller.rb
class ConventionDelegatesController < ApplicationController
  # GET /convention_delegates
  # GET /convention_delegates.json
  def index
    @convention_delegates = ConventionDelegate.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @convention_delegates }
    end
  end

  # GET /convention_delegates/index_mobile
  # GET /convention_delegates/index_mobile.json
  def index_mobile
    @convention_delegates = ConventionDelegate.all

    respond_to do |format|
      format.html # index_mobile.html.erb
      format.json { render json: @convention_delegates }
    end
  end

  # GET /convention_delegates/1
  # GET /convention_delegates/1.json
  def show
    @convention_delegate = ConventionDelegate.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @convention_delegate }
    end
  end

  # GET /convention_delegates/new
  # GET /convention_delegates/new.json
  def new
    @convention_delegate = ConventionDelegate.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @convention_delegate }
    end
  end

  # GET /convention_delegates/1/edit
  def edit
    @convention_delegate = ConventionDelegate.find(params[:id])
  end

  # POST /convention_delegates
  # POST /convention_delegates.json
  def create
    @convention_delegate = ConventionDelegate.new(params[:convention_delegate])

    respond_to do |format|
      if @convention_delegate.save
        format.html { redirect_to @convention_delegate, notice: 'Convention delegate was successfully created.' }
        format.json { render json: @convention_delegate, status: :created, location: @convention_delegate }
      else
        format.html { render action: "new" }
        format.json { render json: @convention_delegate.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /convention_delegates/1
  # PUT /convention_delegates/1.json
  def update
    @convention_delegate = ConventionDelegate.find(params[:id])

    respond_to do |format|
      if @convention_delegate.update_attributes(params[:convention_delegate])
        format.html { redirect_to @convention_delegate, notice: 'Convention delegate was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @convention_delegate.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /convention_delegates/1
  # DELETE /convention_delegates/1.json
  def destroy
    @convention_delegate = ConventionDelegate.find(params[:id])
    @convention_delegate.destroy

    respond_to do |format|
      format.html { redirect_to convention_delegates_url }
      format.json { head :ok }
    end
  end
end

app/helpers/convention_delegates_helper.rb
module ConventionDelegatesHelper
end

app/views/convention_delegates/_form.html.erb
<%= form_for(@convention_delegate) do |f| %>
  <% if @convention_delegate.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@convention_delegate.errors.count, "error") %> prohibited this convention_delegate from being saved:</h2>

      <ul>
      <% @convention_delegate.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :first_name %><br />
    <%= f.text_field :first_name %>
  </div>
  <div class="field">
    <%= f.label :last_name %><br />
    <%= f.text_field :last_name %>
  </div>
  <div class="field">
    <%= f.label :riding %><br />
    <%= f.text_field :riding %>
  </div>
  <div class="field">
    <%= f.label :score %><br />
    <%= f.text_field :score %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/convention_delegates/edit.html.erb
<h1>Editing convention_delegate</h1>

<%= render 'form' %>

<%= link_to 'Show', @convention_delegate %> |
<%= link_to 'Back', convention_delegates_path %>

app/views/convention_delegates/index.html.erb
<h1>Listing convention_delegates</h1>

<table>
  <tr>
    <th>First name</th>
    <th>Last name</th>
    <th>Riding</th>
    <th>Score</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @convention_delegates.each do |convention_delegate| %>
  <tr>
    <td><%= convention_delegate.first_name %></td>
    <td><%= convention_delegate.last_name %></td>
    <td><%= convention_delegate.riding %></td>
    <td><%= convention_delegate.score %></td>
    <td><%= link_to 'Show', convention_delegate %></td>
    <td><%= link_to 'Edit', edit_convention_delegate_path(convention_delegate) %></td>
    <td><%= link_to 'Destroy', convention_delegate, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Convention delegate', new_convention_delegate_path %>

app/views/convention_delegates/index_mobile.html.erb
<h1>Listing convention_delegates</h1>


<ul data-role="listview" data-inset="true" data-filter="true">
<% @convention_delegates.each do |convention_delegate| %>
  <li>
    <a href='<%= url_for convention_delegate %>'>
    <%= convention_delegate.first_name %>
    <%= convention_delegate.last_name %>
    <%= convention_delegate.riding %>
    </a>
  </li>
<% end %>
</ul>

<br />

<%= link_to 'New Convention delegate', new_convention_delegate_path %>

app/views/convention_delegates/new.html.erb
<h1>New convention_delegate</h1>

<%= render 'form' %>

<%= link_to 'Back', convention_delegates_path %>

app/views/convention_delegates/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>First name:</b>
  <%= @convention_delegate.first_name %>
</p>

<p>
  <b>Last name:</b>
  <%= @convention_delegate.last_name %>
</p>

<p>
  <b>Riding:</b>
  <%= @convention_delegate.riding %>
</p>

<p>
  <b>Score:</b>
  <%= @convention_delegate.value %>
</p>


<%= link_to 'Edit', edit_convention_delegate_path(@convention_delegate) %> |
<%= link_to 'Back', convention_delegates_path %>