config/routes.rb
Testsite2::Application.routes.draw do
  match 'user/edit' => 'users#edit', :as => :edit_current_user

  match 'signup' => 'users#new', :as => :signup

  match 'logout' => 'sessions#destroy', :as => :logout

  match 'login' => 'sessions#new', :as => :login

  root :to => 'accounts#new'

  resources :sessions

  match '/mobile/', :controller => 'mobile', :action => 'index'
  match '/mobile/:id', :controller => 'mobile', :action => 'show'
  match '/mobile/:id/observe', :controller => 'mobile', :action => 'observe'
  match '/mobile/:id/create_observation', :controller => 'mobile', :action => 'create_observation'

  get "sessions/new"
  
  resources :users

  resources :convention_delegates

  resources :observations

end

app/controllers/mobile_controller.rb
class MobileController < ApplicationController
  def index
    @convention_delegates = ConventionDelegate.all

    respond_to do |format|
      format.html # index_mobile.html.erb
      format.json { render json: @convention_delegates }
    end
 
  end

  def show
    @convention_delegate = ConventionDelegate.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @convention_delegate }
    end
  end

  def observe
    @convention_delegate = ConventionDelegate.find(params[:id])
  end

  # POST /mobile/1
  # POST /mobile/1.json
  # need to find a way for this to be routed properly
  # also it's not working yet
  def create_observation
    @convention_delegate = ConventionDelegate.find(params[:id])
    logger.debug "The object is..." + params.inspect
    logger.debug "\n"
    logger.debug params['observation']['value'].inspect
    logger.debug "\n"
    params['observation']
    observation_data = {
        :convention_delegate_id => params[:id],
        :user_id => 1, #not actually implemented yet
        :ip_address => request.remote_ip,
        :user_agent => request.env['HTTP_USER_AGENT'],
        :value => Integer(params['observation']['value'])
    } 
    @observation = Observation.new(observation_data)

    respond_to do |format|
      if @observation.save
        format.html { redirect_to '/mobile/', notice: 'Observation was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @convention_delegate.errors, status: :unprocessable_entity }
      end
    end
  end
end

app/helpers/mobile_helper.rb
module MobileHelper
end

app/views/mobile/_form.erb
<%= form_tag(:controller => 'mobile', 
             :convention_delegate => @convention_delegate,
             :action => 'observe') %>  
    <%
        puts @convention_delegate.first_name
        puts @convention_delegate.last_name
        puts @convention_delegate.riding
    %>
  <div class="field">
    <fieldset data-role="controlgroup">
        <legend>Support Level</legend>

        <%= f.label :value %><br />
        <%= f.radio_button :value, 1 %>1
        <%= f.radio_button :value, 2 %>2
        <%= f.radio_button :value, 3 %>3
        <%= f.radio_button :value, 4 %>4
        <%= f.radio_button :value, 5 %>5
    </fieldset>
  </div>
<% end %>

app/views/mobile/index.html.erb
<h1>Listing convention_delegates</h1>


<ul data-role="listview" data-inset="true" data-filter="true" id='delegate_list'>
<% @convention_delegates.each do |convention_delegate| %>
  <li>
  <a href='<%= url_for(:action => 'observe', :id => convention_delegate.id ) %>'>
    <%= convention_delegate.first_name %>
    <%= convention_delegate.last_name %> -- 
    <%= convention_delegate.riding %>
    </a>
  </li>
<% end %>
</ul>

app/views/mobile/observe.html.erb
<h1>Observe &amp; Report</h1>

<%= form_tag(:controller => 'mobile', :action => 'create_observation') do %>  
    
    <%= @convention_delegate.first_name %>
    <%= @convention_delegate.last_name %>
    <%=  @convention_delegate.riding %>
    
  <div class="field">
    <fieldset data-role="controlgroup">
        <legend>Support Level</legend>

        <%= radio_button "observation", :value, 1 %>
        <%= label_tag 'observation_value_1' , "1 - \u{263A}"%>
        <%= radio_button "observation", :value, 2 %>
        <%= label_tag 'observation_value_2' , '2'%>
        <%= radio_button "observation", :value, 3 %>
        <%= label_tag 'observation_value_3' , "3 - \u{1F62A}"%>
        <%= radio_button "observation", :value, 4 %>
        <%= label_tag 'observation_value_4' , '4'%>
        <%= radio_button "observation", :value, 5 %>
        <%= label_tag 'observation_value_5' , "5 - \u{2639}"%>
    </fieldset>
    <%= submit_tag("Submit") %>
  </div>
<% end %>

<%= link_to 'Back', mobile_path %>

app/views/mobile/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>First name:</b>
  <%= @convention_delegate.first_name %>
</p>

<p>
  <b>Last name:</b>
  <%= @convention_delegate.last_name %>
</p>

<p>
  <b>Riding:</b>
  <%= @convention_delegate.riding %>
</p>

<p>
  <b>Score:</b>
  <%= @convention_delegate.score %>
</p>


<%= link_to 'Back', mobile_path %>